# Usage:
#   docker-compose up --force-recreate
version: '3'

services:
  #--------------#

  zendao_bete10:
     
#    build: .
#    dockerfile: Dockerfile
    image: "jamesz2011/zendao_bete10_v1"
    container_name: zendao_bete10
    tty: true
    volumes:
      - /opt/zendao-data:/opt/zbox
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 8022:8080
      - 3312:3306
     

    restart: always
